name: Update ledger-ethics submodule

on:
  schedule:
    # Runs every Monday at 03:00 UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update ledger-ethics to latest commit
        run: |
          git submodule update --remote vendor/ledger-ethics
          # Only commit if there are changes
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: update ledger-ethics submodule"
          fi

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-ledger-ethics-${{ github.run_number }}
          title: 'chore: update ledger-ethics submodule'
          body: |
            This is an automated PR to refresh the **ledger-ethics** submodule to the latest commit on its default branch.

            Merge when CI passes.
          commit-message: 'chore: update ledger-ethics submodule' 